# Site settings
title: flesh and the power it holds ~
description: Get to know flesh.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: flesh
user_description: My name is Gonzalo Antonicelli, I'm 28 years old, and I'm based in Buenos Aires, Argentina, in the beautiful neighborhood of Palermo. I've worked as a QA Tester, iOS front-end developer, DevOps engineer. Now I'm working my first international job, in a web3 / crypto enviroment where I'm constantly learning new and exciting stuff. I'm currently leading the Customer Support area at Fleek, a platform that allows you to deploy to IPFS and the Internet Computer.
user_title: CS for Fleek & PsychedelicDAO
email: gonzalo@fleek.com
twitter_username: psyflesh
github_username:  fleekgonzalo
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
